@startuml
!define AWSPuml https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/v18.0/dist/
!includeurl AWSPuml/AWSCommon.puml
!includeurl AWSPuml/Compute/Lambda.puml
!includeurl AWSPuml/Database/DynamoDB.puml
!includeurl AWSPuml/ManagementGovernance/CloudWatch.puml
!includeurl AWSPuml/ApplicationIntegration/APIGateway.puml

!includeurl AWSPuml/Groups/AWSAccount.puml
!includeurl AWSPuml/Groups/VPC.puml
!includeurl AWSPuml/Groups/Region.puml

RegionGroup(aws_region, "AWS Region") {
    AWSAccountGroup(aws_account, "AWS Account") {
        VPCGroup(aws_vpc, "AWS VPC") {
            APIGateway(api_gateway, "API Gateway", "Url Shortener ApiGW")
            Lambda(lambda_function, "AWS Lambda", "Url Shortener Function handler")
            DynamoDB(dynamo_table, "DynamoDB", "Url Shortener Table for storage")
            CloudWatch(cloudWatch_logs, "CloudWatch", "Monitoring logs")
        }
    }
}


api_gateway --> lambda_function : "Invoke"
lambda_function --> dynamo_table : "Read/Write"
lambda_function --> cloudwatch_logs : "Send Logs"
@enduml